rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ree
  - jruby
  - rbx
gemfile:
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/datamapper.gemfile
  - gemfiles/mongoid.gemfile
services:
  - mongodb
matrix:
  allow_failures:
    - rvm: rbx
notifications:
  recipients:
    - bryan@bryanrite.com
